### ISSUE TITLE
The drop down menu lags

### ISSUE THREAD

**Issue by gapplef** [konkor/obmin#10]
Latest obmin gnome shell extension on ubuntu 17.10
The appear of drop down menu always lags, not only on 17.10, but also on 16.04, 17.04.
The lags really annoying, please fix it.

**Comment by konkor** [comment]
I'm sorry for this issue.
Can you tell more about your obmin installation, desktop environment and the lag. Is it delay on the opening? It was fixed... Did you install obmin from gnome repo or manually from deb/zip package?
Anyway try to install next not released version yet:
https://extensions.gnome.org/review/download/7546.shell-extension.zip
or from GitHub
https://github.com/konkor/obmin/tree/master/releases

**Comment by gapplef** [comment]
Desktop Environment: Ubuntu Gnome 16.04、Ubuntu 17.10
I install the extension from the website https://extensions.gnome.org
The appear of drop down menu delays when:
1. click the obmin icons on panel
2. open the drop down menu with other icons, and move to the obmin icon

**Comment by gapplef** [comment]
Seems the pre-release version fixed the problem, Thank you!

**Comment by konkor** [comment]
@gapplef try this version https://extensions.gnome.org/review/download/7546.shell-extension.zip
You can just extract and replace the extension folder files with the archive's content. After that re-log you gnome session.
Oh glad to hear this.

**Comment by gapplef** [comment]
Thanks for your excellent work.

**Comment by konkor** [comment]
@gapplef if you have any issues or comment just pull an issue. I need a some feedback I don't really know what is users wants. So it's very complex project here is server, own framework, backends and frontends and all gui tools... I have fixed your bug twice :(
I think a few releases I'll make extra server applications. Now I'm working on slideshow viewer. After I'll make Audio player, Video transcoder... I don't know RSS feeds? Radio Stations?

**Comment by gapplef** [comment]
As a file sharing application, my user case are mainly the following two:
1. File share which is already very ease to use.
2. Video streaming from PC to my Phone. Current the mp4 can be streaming with browser on my phone. With my Laptop's self host hotspot, things works quite well. But other video format like mkv can't be streamed, an android application that support video streaming would help.

And if you want more feedback, I think you should share the application on [Reddit](https://www.reddit.com/r/linux/) or other place. I find this application when I read the Google plus post of WOGUE.

**Comment by konkor** [comment]
@gapplef thanks again for your response!
About video streaming MKV or other formats. **Did you see https://youtu.be/mSj8b1x7_bw ?** I wasted almost 2 weeks on it. There you could see how to open any format in an external video/media player (in the video I used Smplayer but it works in Totem, VLC) for desktops.
The same method works very well on mobile devices. I'm using Firefox/Chrome and BS Player Free or VLC Player on Android.
**So I don't recommend to use embedded players in browsers at all!!! Their are wasting a huge of RAM to cache whole video file when external players working with buffer 1-2 MB only!**

------
So the obmin streaming works very well it cannot convert on the fly but streams it's basic Obmin Feature it supporting Ranges (so you can even use a seek-bar in players) and Multiple Connections (you can download 1 large file in a few streams)...

**Comment by konkor** [comment]
@gapplef Oh forget about mplayer extension for Firefox to an example or VLC extension...
So Firefox has many helpers/addons for most popular video players to open in VLC, SMPlayer...
So I'm using M3U playlists to listen music on Android devices in VLC player (any FLAC, MP3, OGG, MPA...)

**Comment by konkor** [comment]
@gapplef at the end about Reddit or other media... It needs more attention to reply on all comments and some people don't make difference between Address Bar and Google Search Bar....
**But if you make some post about the project I would glad to join and answer if it needs**

**Comment by konkor** [comment]
@gapplef Completely forget, I made G+ OBMIN Community 
https://plus.google.com/u/0/communities/111793545135238329562
You could ask your question there and maybe it helps other find their issues out. So I could collect some info in the How-to or make a right decision on a next milestone.
**I'll glad to see you there with some questions. :)**
Thank you!
