### ISSUE TITLE
local ip address is set to 127.0.0.1

### ISSUE THREAD

**Issue by focmb** [konkor/obmin#11]
Hi,

on my notebook I use a USB-Lan-Adapter. It is called usb0 in my network settings. The obmin gnome shell extension doesn't detect this and is running with the loop back adapter (127.0.0.1). But with this loop back adapter I cant share files with others. 

Is it possible to tell the obmin extension which network interface should be used?

**Comment by konkor** [comment]
Hi, @focmb! Can you provide an output of the:
```
hostname -I
```
and:
```
sudo ifconfig
```
Actually, Obmin server runs on all network devices like eth, wlan and virtual devices (VPN, Qemu and others)...
No, it's not possible to tell the extension which device to use now. But It's possible to do in future versions.
Thanks for report! It could make the application better.

**Comment by focmb** [comment]
```
hostname -i
192.168.213.64 
```
```
└─▶sudo ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 28  bytes 2580 (2.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28  bytes 2580 (2.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.213.64  netmask 255.255.255.0  broadcast 192.168.213.255
        ether 00:50:b6:1d:e3:7d  txqueuelen 1000  (Ethernet)
        RX packets 37261  bytes 38876106 (37.0 MiB)
        RX errors 0  dropped 5783  overruns 0  frame 0
        TX packets 15696  bytes 1255327 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by konkor** [comment]
@focmb sorry for the delay. I was on a vacation.
I will fix it soon.
Thank you for the report!
