### ISSUE TITLE
the fix for the local IP doesn't work

### ISSUE THREAD

**Issue by focmb** [konkor/obmin#12]
Hi,

today i installed the new version of your extension with the fix for the local IP address. But the fix doesn't work on my manjaro linux.

In your fix you are using: ("hostname -I") but if I type this in a termina I get:
    
    └─▶hostname -I
    hostname: invalid option -- 'I'
    Try 'hostname --help' or 'hostname --usage' for more information.
![bildschirmfoto von 2018-05-01 17-47-43](https://user-images.githubusercontent.com/261217/39480240-e19b99e0-4d67-11e8-90bf-c39d7b9469de.png)

If I change "hostname -I" by "hostname -i" in extension.js, common/center.js and common/indicator.js all is working fine

![bildschirmfoto von 2018-05-01 17-52-18](https://user-images.githubusercontent.com/261217/39480436-77ea879e-4d68-11e8-814c-feda38c1bc3d.png)

**Comment by konkor** [comment]
@focmb thank you for testing and reporting again!
I think it's fixed on master branch now. It will be able on gnome repo too but I don't know when.
