### ISSUE TITLE
Issue in Raspberry pi 4 

### ISSUE THREAD

**Issue by MMZCustoms** [konkor/obmin#14]
when using continuesely for 10 min, server getting hang and have to restart the server. This issue happens only in raspberry pi 4 and pi 3 is working good.

**Comment by konkor** [comment]
@MMZCustoms Unfortunately, I don't have RPi4 to check this issue. Are you using gui or just server application?

**Comment by MMZCustoms** [comment]
I am using server application in rpi4

**Comment by sijumanuel** [comment]
We are also facing similar issues in raspbery pi 4.
Then we tried to cross-check with raspberry pi 3,with 5 connections similar issue observed after 30 minutes

**Comment by MMZCustoms** [comment]
please check this log


(obmin-server:2253): Gjs-CRITICAL **: 20:09:13.466: The offending signal was wrote-chunk on SoupMessage 0x86ddf8.
== Stack trace for context 0x672840 ==
#0         8295b8 i   resource:///org/gnome/gjs/modules/mainloop.js:36 (b169d5d8 @ 65)
#1         829548 i   /usr/share/gnome-shell/extensions/obmin@konkor/common/server.js:891 (b1692f30 @ 2115)
#2         8294e8 i   /usr/bin/obmin-server:17 (b1666160 @ 129)

(obmin-server:2253): Gjs-CRITICAL **: 20:09:13.467: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

**Comment by MMZCustoms** [comment]
@konkor please help us to solve this issue.

**Comment by konkor** [comment]
@MMZCustoms I will try to locate the issue in RPI emulator. I'm on vacation right now.

**Comment by ronypulickan** [comment]
### please check this log,obmin server running on Raspbian Buster
[putty.log](https://github.com/konkor/obmin/files/3440576/putty.log)

**Comment by sijumanuel** [comment]
Any updates

**Comment by ronypulickan** [comment]
@konkor any updates

**Comment by sijumanuel** [comment]
any updates

**Comment by konkor** [comment]
I can't find a way to test the app in a virtual machine. So I'm going to buy RPI... Can you recommend what version of RPI I should buy? I'm choosing between RPI4 B (1GB/2GB/4GB) or RPI3 B+ 1GB...

BTW I could make some optimisations meanwhile. How are you installing it from git or DEB package?

**Comment by sijumanuel** [comment]
Better to buy RPI4 B (2GB/4GB).
We are using deb package

**Comment by konkor** [comment]
Can you test the current changes [Latest DEB package](https://github.com/konkor/obmin/raw/master/releases/obmin_latest_all.deb)??? Thanks!

**Comment by konkor** [comment]
I think It can be closed. Finally, I bought RPI4 and testing it a few days without any issues on Raspbian Buster.

BTW, I'm a bit disappointed in the RPI4:
1. No open-source video drivers. So There is no other distributions or OS for it.
2. It's very hot and you have to place a massive radiator before using it.
3. No HW accelerated codecs for VP9, h265... Also h264 decoding is not perfect even on 1080p.

I would recommend some other alternatives like Pine64 Rock64 media board etc.

**Comment by MMZCustoms** [comment]
Thank you for your support,
