### ISSUE TITLE
Will not start server when enabling user authentication

### ISSUE THREAD

**Issue by joshontech** [konkor/obmin#15]
I am using OBmin version 19 on centOS 8.
I can add folders and change any other settings but when trying to set a user name and password the server will not start. 
What happens exactly is when I check the box for user authentication and than click the power symbol to start the server it never starts. Once and a while it starts for a split second and than stops immediately.
If you need any additional information just let me know. 
Love this project making my server life a ton easier!

**Comment by konkor** [comment]
@joshontech Thanks for the report. I fixed the issue and I will push updates soon.
