### ISSUE TITLE
No public IP

### ISSUE THREAD

**Issue by deikatsuo** [konkor/obmin#4]
![screenshot from 2017-07-27 04-18-59](https://user-images.githubusercontent.com/8337409/28644208-d55c48d4-7282-11e7-906a-3ee187d0ae0a.png)

**Comment by konkor** [comment]
TY for ur reports. Can you tell about your distribution, please? Here is no one way to detect IP on all Linux distributions.

**Comment by deikatsuo** [comment]
Archlinux x64, Gnome 3.24

**Comment by deikatsuo** [comment]
Btw, I am using WIFI ( tethering from Android ) as my internet connection

**Comment by konkor** [comment]
Try install [bind-tools](https://www.archlinux.org/packages/extra/x86_64/bind-tools/) for Arch... You need 'dig' command to show Public IP. BTW What's your output for
```
dig +short myip.opendns.com @resolver1.opendns.com
```

and for local IP You need the package [inetutils](https://www.archlinux.org/packages/core/x86_64/inetutils/)
```
hostname -I
```

**Comment by konkor** [comment]
For Debian/Ubuntu/Fedora and Co they are default packages...

**Comment by deikatsuo** [comment]
blank
`dig +short myip.opendns.com @resolver1.opendns.com`
![screenshot from 2017-07-27 05-02-01](https://user-images.githubusercontent.com/8337409/28645719-d0060c16-7288-11e7-85ab-49ed24ed0bb6.png)

**Comment by konkor** [comment]
dig method uses a DNS request to detect public IP... Check your firewall setting for DNS port for UDP protocol (port 53 UDP)...

**Comment by deikatsuo** [comment]
hostname -i
![screenshot from 2017-07-27 05-09-09](https://user-images.githubusercontent.com/8337409/28646010-c17c6946-7289-11e7-87f9-139b88d1c883.png)

**Comment by deikatsuo** [comment]
![screenshot from 2017-07-27 05-11-11](https://user-images.githubusercontent.com/8337409/28646074-09494708-728a-11e7-9d75-ab34e3ac17a1.png)

**Comment by deikatsuo** [comment]
dig myip.opendns.com @resolver1.opendns.com

> ; <<>> DiG 9.11.1-P1 <<>> myip.opendns.com @resolver1.opendns.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58837
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;myip.opendns.com.		IN	A
> 
> ;; AUTHORITY SECTION:
> opendns.com.		6564	IN	SOA	auth1.opendns.com. noc.opendns.com. 1501094315 16384 2048 1048576 2560
> 
> ;; Query time: 44 msec
> ;; SERVER: 208.67.222.222#53(208.67.222.222)
> ;; WHEN: Thu Jul 27 05:13:50 WIB 2017
> ;; MSG SIZE  rcvd: 91

![screenshot from 2017-07-27 05-14-02](https://user-images.githubusercontent.com/8337409/28646153-81068eae-728a-11e7-81dd-046bb13785e1.png)

**Comment by konkor** [comment]
so `hostname` shows wrong local IP? heh 131 and 132...
About external/public... It's look like DNS method can be complicated for many people. I'll think about it too... So I'll test on Android tethering... I don't know if Android can port mapping HTTP port, you could try to set 80 port directly in the prefs window for the server so...

**Comment by deikatsuo** [comment]
no, actually `hostname` is shown the right one 192.168.43.131
![screenshot from 2017-07-27 05-27-39](https://user-images.githubusercontent.com/8337409/28646553-6c29849e-728c-11e7-8168-e511fb0ccda5.png)

**Comment by konkor** [comment]
I though I'll update public IP getting from DNS to WEB method soon.
About Android Wi-Fi hotspot: All devices connected to it will be work but external IP doesn't work for my mobile provider or my hardware. I have googled about it and most mobile providers are blocking inbound connections... So I see only one way to fix it is using VPN services.
PS: VPN can grant some secure level too like HTTPS with authorization so.
